version: '3.8'

services:
  backend-meli:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend-meli:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend-meli